<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Shared\Domain\ValueObjects\Uuid;
use Illuminate\Support\Facades\DB;

class CarBrandsSeeder extends Seeder
{
    public function run()
    {
        $brands = [
            ['id' => Uuid::random()->value(), 'value' => 'acura', 'name' => 'Acura',  'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'alfa-romeo', 'name' => 'Alfa Romeo',  'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'aptera', 'name' => 'Aptera',  'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'aston-martin', 'name' => 'Aston Martin',  'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'audi', 'name' => 'Audi',  'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'austin', 'name' => 'Austin', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'bentley', 'name' => 'Bentley', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'bmw', 'name' => 'BMW', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'bugatti', 'name' => 'Bugatti', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'buick', 'name' => 'Buick', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'cadillac', 'name' => 'Cadillac', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'chevrolet', 'name' => 'Chevrolet', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'chrysler', 'name' => 'Chrysler', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'citroen', 'name' => 'Citroën', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'corbin', 'name' => 'Corbin', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'daewoo', 'name' => 'Daewoo', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'daihatsu', 'name' => 'Daihatsu', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'dodge', 'name' => 'Dodge', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'eagle', 'name' => 'Eagle', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'fairthorpe', 'name' => 'Fairthorpe', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'ferrari', 'name' => 'Ferrari', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'fiat', 'name' => 'FIAT', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'fillmore', 'name' => 'Fillmore', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'foose', 'name' => 'Foose', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'ford', 'name' => 'Ford', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'geo', 'name' => 'Geo', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'gmc', 'name' => 'GMC', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'hillman', 'name' => 'Hillman', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'holden', 'name' => 'Holden', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'honda', 'name' => 'Honda', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'hummer', 'name' => 'HUMMER', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'hyundai', 'name' => 'Hyundai', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'infiniti', 'name' => 'Infiniti', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'isuzu', 'name' => 'Isuzu', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'jaguar', 'name' => 'Jaguar', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'jeep', 'name' => 'Jeep', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'jensen', 'name' => 'Jensen', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'kia', 'name' => 'Kia', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'lamborghini', 'name' => 'Lamborghini', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'land-rover', 'name' => 'Land Rover', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'lexus', 'name' => 'Lexus', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'lincoln', 'name' => 'Lincoln', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'lotus', 'name' => 'Lotus', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'maserati', 'name' => 'Maserati', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'maybach', 'name' => 'Maybach', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'mazda', 'name' => 'Mazda', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'mclaren', 'name' => 'McLaren', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'mercedes-benz', 'name' => 'Mercedes-Benz', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'mercury', 'name' => 'Mercury', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'merkur', 'name' => 'Merkur', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'mg', 'name' => 'MG', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'mini', 'name' => 'MINI', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'mitsubishi', 'name' => 'Mitsubishi', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'morgan', 'name' => 'Morgan', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'nissan', 'name' => 'Nissan', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'oldsmobile', 'name' => 'Oldsmobile', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'panoz', 'name' => 'Panoz', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'peugeot', 'name' => 'Peugeot', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'plymouth', 'name' => 'Plymouth', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'pontiac', 'name' => 'Pontiac', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'porsche', 'name' => 'Porsche', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'ram', 'name' => 'Ram', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'rambler', 'name' => 'Rambler', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'renault', 'name' => 'Renault', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'rolls-royce', 'name' => 'Rolls-Royce', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'saab', 'name' => 'Saab', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'saturn', 'name' => 'Saturn', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'scion', 'name' => 'Scion', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'shelby', 'name' => 'Shelby', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'smart', 'name' => 'Smart', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'spyker', 'name' => 'Spyker', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'spyker-cars', 'name' => 'Spyker Cars', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'studebaker', 'name' => 'Studebaker', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'subaru', 'name' => 'Subaru', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'suzuki', 'name' => 'Suzuki', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'tesla', 'name' => 'Tesla', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'toyota', 'name' => 'Toyota', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'volkswagen', 'name' => 'Volkswagen', 'status' => 'active'],
            ['id' => Uuid::random()->value(), 'value' => 'volvo', 'name' => 'Volvo', 'status' => 'active'],
        ];

        DB::table('cars_brand')->insert($brands);
    }
}
