version: '3.7'
services:
  composer:
    image: composer:2.3.9
    container_name: composer
    volumes:
      - ./:/app
    depends_on:
      - app
    networks:
      - quicktrack_network
    command: "composer install"

  mariadb:
    image: mariadb:10.8.3-jammy
    container_name: mariadb
    restart: always
    environment:
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    networks:
      - quicktrack_network
    volumes:
      - mariadb-data:/var/lib/mysql
      - mariadb-config:/etc/mysql

  app:
    #image: php:8.1-apache
    build:
      context: .
      dockerfile: Dockerfile
      args:
          user: developer
          uid: 1000
    container_name: quicktrack
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www/html
    networks:
      - quicktrack_network
    depends_on:
      - mariadb
    command: "php artisan serve --host=0.0.0.0"

networks:
  quicktrack_network:

volumes:
    mariadb-data:
    mariadb-config:
