<?php

namespace Tests\Shared\Infrastructure\Laravel;

use Firebase\JWT\JWT;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Quicktrack\User\Infrastructure\Eloquent\Models\User;
use Shared\Domain\Errors;
use Tests\TestCase as LaravelTestCase;

abstract class TestCase extends LaravelTestCase
{
    use DatabaseTransactions;
    protected $token;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $key = env('JWT_SECRET');
        $jwtAlgo = env('JWT_ALGO');

        $user = User::factory()->create();
        $time = time();
        $timenbf = $time - 460;

        $payload = [
            "iss" => getenv('APP_URL'), //emisor
            "sub" => $user->id,
            "iat" => $time,
            "nbf" => $timenbf,
            "exp" => $time + 10,
            "data" => [
                'id' => $user->id,
                'email' => $user->email,
                'name' => $user->name
            ]
        ];
        $this->token = JWT::encode($payload, $key, $jwtAlgo);
    }

    protected function tearDown(): void
    {
        if (Errors::getInstance()->hasErrors()) {
            Errors::getInstance()->clear();
        }
    }
}
